image: php:7.1

stages:
- test

# PHP lint
## Anchor
.php_lint_template: &php_lint_template
  stage: test
  script:
  - for f in $(find src -name '*.php'); do php -l $f; done

## General
php-lint:
  image: php:7.1-alpine
  <<: *php_lint_template

## Other versions
php-lint:php5.6:
  image: php:5.6-alpine
  <<: *php_lint_template

php-lint:php7.0:
  image: php:7.0-alpine
  <<: *php_lint_template

php-lint:php7.2-rc:
  image: php:7.2-rc-alpine
  <<: *php_lint_template

# Anchor for composer cache
.composer_cache: &composer_cache
  cache:
    paths:
    - .composercache
    - vendor/apt

# Style check
phpcs:
  <<: *composer_cache
  stage: test
  before_script:
  # Install composer
  - mkdir -p vendor/apt
  - apt-get update -yqq
  - apt-get -o dir::cache::archives="vendor/apt" install zip unzip git -yqq
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar config cache-files-dir .composercache
  - php composer.phar install
  script:
    - vendor/bin/phpcs --error-severity=1 --warning-severity=8 --extensions=php

# Unit test
## Anchors
.units_install_deps: &units_install_deps |
  # Install composer
  mkdir -p vendor/apt
  apt-get update -yqq
  apt-get -o dir::cache::archives="vendor/apt" install zip unzip git -yqq
  curl -sS https://getcomposer.org/installer | php
  php composer.phar config cache-files-dir .composercache
  php composer.phar install
  # Install and enable MySQL
  docker-php-ext-install mysqli
  docker-php-ext-enable mysqli

.units_template: &units_template
  <<: *composer_cache
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: legionboard
    MYSQL_ROOT_PASSWORD: mysql
  script:
  - vendor/bin/atoum

## General

units:
  <<: *units_template
  coverage: '/Code coverage value: \d+\.\d+/'
  before_script:
  - *units_install_deps
  # Xdebug is needed for coverage
  - pecl install xdebug
  - docker-php-ext-enable xdebug

units:php5.6:
  image: php:5.6
  <<: *units_template
  before_script:
  - *units_install_deps

units:php7.0:
  image: php:7.0
  <<: *units_template
  before_script:
  - *units_install_deps

units:php7.2-rc:
  image: php:7.2-rc
  <<: *units_template
  before_script:
  - *units_install_deps
